# Generated by Django 2.2 on 2019-04-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favourite_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_description', models.CharField(max_length=150)),
                ('location', models.BooleanField(blank=True, default=False)),
                ('image_url', models.CharField(blank=True, max_length=400)),
                ('skill_set', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='supplier',
            name='photo_url',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='product',
            name='guru',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, related_name='Gurus', to='favourite_app.Guru'),
            preserve_default=False,
        ),
    ]
