# Generated by Django 2.2 on 2019-04-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=75),
        ),
    ]
