# Generated by Django 2.2 on 2019-04-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite_app', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='name',
            field=models.CharField(default=False, max_length=75),
        ),
    ]
