# Generated by Django 2.2 on 2019-04-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite_app', '0004_guru_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=False, max_length=75),
        ),
    ]
